version: '3.8'

services:
  # Eureka Server
  eureka-server:
    image: him1502/eureka-server:v1
    container_name: eureka-server-container
    ports:
      - "8761:8761"
    networks:
      - healthcare-network
    environment:
      - EUREKA_INSTANCE_HOSTNAME=eureka-server

  # API Gateway
  api-gateway:
    image: him1502/api-gateway:v1
    container_name: api-gateway-container
    ports:
      - "8081:8081"
    networks:
      - healthcare-network
    depends_on:
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    ports:
      - "3306:3306"
    networks:
      - healthcare-network
    environment:
      MYSQL_ROOT_PASSWORD: himanshu
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  # Patient Service
  patient-service:
    image: him1502/patient-service:v1
    container_name: patient-service-container
    ports:
      - "8083:8083"
    networks:
      - healthcare-network
    depends_on:
      - eureka-server
      - api-gateway
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/patientdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=himanshu
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  # Doctor Service
  doctor-service:
    image: him1502/doctor-service:v1
    container_name: doctor-service-container
    ports:
      - "8082:8082"
    networks:
      - healthcare-network
    depends_on:
      - eureka-server
      - api-gateway
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/doctordb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=himanshu
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

  # Appointment Service
  appointment-service:
    image: him1502/appointment-service:v1
    container_name: appointment-service-container
    ports:
      - "8084:8084"
    networks:
      - healthcare-network
    depends_on:
      - eureka-server
      - api-gateway
      - mysql
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/appointmentdb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=himanshu
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka

networks:
  healthcare-network:
    driver: bridge

volumes:
  mysql-data: