# Secret: MySQL root password
apiVersion: v1
kind: Secret
metadata:
  name: doctor-mysql-secret
  namespace: healthcare
type: Opaque
data:
  mysql-root-password: aGltYW5zaHU=  # base64 for "himanshu"

---

# ConfigMap: MySQL DB name
apiVersion: v1
kind: ConfigMap
metadata:
  name: doctor-mysql-config
  namespace: healthcare
data:
  mysql-database-name: "doctordb"

---

# Persistent Volume Claim (PVC)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: doctor-mysql-pvc
  namespace: healthcare
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi

---

# MySQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctor-mysql
  namespace: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doctor-mysql
  template:
    metadata:
      labels:
        app: doctor-mysql
    spec:
      containers:
        - name: doctor-mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: doctor-mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: doctor-mysql-config
                  key: mysql-database-name
          volumeMounts:
            - name: mysql-storage
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-storage
          persistentVolumeClaim:
            claimName: doctor-mysql-pvc

---

# MySQL Service
apiVersion: v1
kind: Service
metadata:
  name: doctor-mysql
  namespace: healthcare
spec:
  selector:
    app: doctor-mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP