apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-init-script
  namespace: healthcare
data:
  init.sql: |
    CREATE DATABASE IF NOT EXISTS doctordb;
    CREATE DATABASE IF NOT EXISTS patientdb;
    CREATE DATABASE IF NOT EXISTS appointmentdb;